use crate::tokens::span::Span;
use either::Either;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum IdentKind {
    DEFAULT(String),
    BACKTICK(String),
}

pub type Literal = Vec<Either<String, Vec<Token>>>;
#[derive(Clone, Debug, Eq, PartialEq)]
#[allow(non_camel_case_types, unused)]
pub enum Token {
    ANGLE_LEFT,
    ANGLE_RIGHT,
    BRACE_LEFT,
    BRACE_RIGHT,
    PAREN_LEFT,
    PAREN_RIGHT,
    BRACKET_LEFT,
    BRACKET_RIGHT,
    LEFT_GTE,
    RIGHT_GTE,
    EQ,
    N_EQ,
    COLON,
    SUBTRACT,
    SUM,
    MUL,
    DIV,
    MOD,
    BIT_AND,
    AND,
    OR,
    BIT_XOR,
    BIT_NOT,
    BIT_ZERO_FILL_LEFT_SHIFT,
    BIT_S_RIGHT_SHIFT,
    BIT_ZERO_FILL_RIGHT_SHIFT,
    HASH,
    AT,
    QMARK,
    EXCL_MARK,
    BACKSLASH,
    COMMA,
    SEMI_COLON,
    LINE_BREAK,
    PIPE,
    PERIOD,
    DOUBLE_COLON,
    KEYWORD_VAR,
    KEYWORD_VAL,
    KEYWORD_CONST,
    MOD_KEYWORD_ONCE,
    MOD_KEYWORD_PUBLIC,
    MOD_KEYWORD_PROTECTED,
    MOD_KEYWORD_INTERNAL,
    KEYWORD_FUNC,
    KEYWORD_CLASS,
    KEYWORD_IMPL,
    KEYWORD_FOR,
    KEYWORD_RETURN,
    KEYWORD_BREAK,
    KEYWORD_CONTINUE,
    KEYWORD_STRUCT,
    KEYWORD_AWAIT,
    KEYWORD_IN,
    KEYWORD_WHILE,
    KEYWORD_MATCH,
    KEYWORD_ENUM,
    KEYWORD_TRY,
    KEYWORD_CATCH,
    KEYWORD_THIS,
    KEYWORD_TYPE,
    KEYWORD_CONSTRUCTOR,
    KEYWORD_CLASSDEF,
    KEYWORD_FUNCDEF,
    KEYWORD_USE,
    KEYWORD_EXT,
    KEYWORD_OPERATOR,
    KEYWORD_DECORATOR,
    KEYWORD_REFLECT,
    KEYWORD_INTERFACE,
    KEYWORD_IF,
    KEYWORD_ELSE,
    KEYWORD_ELSE_IF,
    KEYWORD_YIELD,
    OP_SPREAD,
    IDENT(IdentKind),
    ASSIGN,
    ASSIGN_SUM,
    ASSIGN_DIV,
    ASSIGN_MOD,
    ASSIGN_MUL,
    ASSIGN_SUB,
    INCR,
    DECR,
    PWR,
    ARROW,
    LITERAL_DOUBLE(Literal),
    LITERAL_SINGLE(Literal),
    OP_FUNC_SUM,
    OP_FUNC_DIV,
    OP_FUNC_MOD,
    OP_FUNC_SUB,
    WJL_COMPILER_PLACEHOLDER,
    DELIMITER,
    WHITESPACE,
    PIPE_OP,
    FLOAT(String),
    INT(String, bool),
    BINARY_NUMBER(String, bool),
    OCTAL_NUMBER(String, bool),
    HEX_NUMBER(String, bool),
    NONCE,
}
